kind: pipeline
name: Incubator

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: setup&build
    image: ubuntu:latest
    environment:
      GITID:
        from_secret: git_id
      GITPWD:
        from_secret: git_pwd
      bot_token:
        from_secret: bot_token
      chat_id:
        from_secret: chat_id
    commands:
      - export HOME=/drone
      - cd ${HOME}
      - apt-get update && apt-get install -y build-essential bc python curl git zip gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev wget libfl-dev bison
      - git clone https://$GITID:$GITPWD@github.com/Ratoriku/msm-4.19 -b staging --depth=1 kernel
      - git clone --depth=1 https://github.com/Ratoriku/AnyKernel3.git -b 4.19
      - git clone --depth=1 https://github.com/kdrag0n/proton-clang.git cbl
      - cd kernel
      - ./ci-build
